### ISSUE TITLE
Errors for AC790/MDM9230

### ISSUE THREAD

**Issue by QuantumBoolean** [bkerler/SierraWirelessGen#10]
Tried with 
`./sierrakeygen.py -l <code> -d MDM9x30` 
and also `-m <code>` for MEP a few times. Always get an error on response.

> AC790-100EUS_NTG9X35C_11.11.17.00_EMEA_04.00
> Product: AirCard 790S
> Revision: 40
> Main:  MDM9230 (2.1)

Some generic AT!OPENLOCK?
```
5A190FB0FFAB6E75
1C826986DF5B7D21
3963E009F984AE00
```

Some generic AT!OPENMEP?
```
65387BFB7549CC51
A84266A2F2F37C47
4DC19BC7246FDE98
```

Need anything else? Thanks.

**Comment by jbgtenn423** [comment]
Same with 791L series.  I attached modem.elf link if needed

https://onedrive.live.com/download?cid=E7AB0009973E983A&resid=E7AB0009973E983A%21703&authkey=AFt-rVxtGokAUO0

.

**Comment by bkerler** [comment]
I've added support with latest commit 1d2851b. Please test using option -d MDM9x30_V1 and report back :)

**Comment by sand-rey** [comment]
Still not works
`AT!OPENMEP?
2BB5AFC663A3A0FC
--
E:\SierraWirelessGen_new>sierrakeygen.py -m 2BB5AFC663A3A0FC -d MDM9x30_V1
AT!OPENMEP="11B20931159EFF8B"
--
AT!OPENMEP="11B20931159EFF8B"
ERROR`
`ati
Manufacturer: Netgear, Incorporated
Model: AC791L
Revision: NTG9X35C_02.08.29.00 r4761 ntgrbc-fwbuild2 2015/08/08 08:01:43
MEID: 35907106096594
ESN: 1281535XXXX, 80EAXXXX
IMEI: 35907106096XXXX
IMEI SV: 0
FSN: 4A515BPK089C8
+GCAP: +CIS707-A, CIS-856, CIS-856-A, +CGSM, +CLTE2, +MS, +ES, +DS, +FCLASS`

**Comment by sand-rey** [comment]
Still error
`AT!OPENMEP?
2BB5AFC663A3A0FC
E:\SierraWirelessGen_new>sierrakeygen.py -m 2BB5AFC663A3A0FC -d MDM9x30_V1
AT!OPENMEP="11B20931159EFF8B"
AT!OPENMEP="11B20931159EFF8B"
ERROR`

> ati
Manufacturer: Netgear, Incorporated
Model: AC791L
Revision: NTG9X35C_02.08.29.00 r4761 ntgrbc-fwbuild2 2015/08/08 08:01:43
MEID: 35907106096594
ESN: 1281535XXXX, 80EAXXXX
IMEI: 35907106096XXXX
IMEI SV: 0
FSN: 4A515BPK089C8
+GCAP: +CIS707-A, CIS-856, CIS-856-A, +CGSM, +CLTE2, +MS, +ES, +DS, +FCLASS`

**Comment by bkerler** [comment]
I've switched the keys. Please retry using commit 8caa580

**Comment by jbgtenn423** [comment]
That Worked : )
