### ISSUE TITLE
Possible to add SDX50M support?

### ISSUE THREAD

**Issue by hazarjast** [bkerler/SierraWirelessGen#12]
This is a most useful tool, thank you! Might it be possible to add SDX50M chipset support for Sierra/Netgear modems like the MR5000? I have seen more in use lately and I would be happy to supply any output as required. Thanks for your consideration.

**Comment by bkerler** [comment]
Yes, I might have a look ;)

**Comment by bkerler** [comment]
I couldn't find any firmware update ... once I get it, I will try to add support.

**Comment by bkerler** [comment]
SDX50M support will be added soon.
