### ISSUE TITLE
Updating Script

### ISSUE THREAD

**Issue by oleteacher** [bkerler/SierraWirelessGen#15]
Amateur learner of Python question:

What is the easiest way to update SierraWirelessGen on my local machine? Like to keep it up with your changes.

I know to install fairly simple:

```
~> git clone https://github.com/bkerler/SierraWirelessGen
~> chmod +x SierraWirelessGen/sierrakeygen.py
~> pip3 install -r requirements.txt
```

But what about updates?

Thanks for sharing and your time.

**Comment by carver-ua** [comment]
многие подписаны на уведомления, и нам приходят email. 
зачем задавать такие простые вопросы ?
купите Windows для чайников. 
diff/fc/git  - там должны быть описанны.

**Comment by oleteacher** [comment]
@carver-ua So sorry that I bothered you and yes I am a USA dummy. Why such an attack?

People like you war why the world is bad.

**Comment by tpoechtrager** [comment]
Sadly some people are like this. They think they are something 'better', an 'elite' or whatever they think.

`git pull`

Is probably what you are looking for.

He didn't write USA dummy though. Google Translate is very bad. Use deepl.com instead.

**Comment by oleteacher** [comment]
Thanks @tpoechtrager . In some ways he is right, I probably should have used Stackoverflow for question like this, but it is even worse. Lot of great people there (like here) but so many think they are gods gift to intelligence :) We all start at the bottom of learning and that is where I am with Python.

Thank you for taking time to provide the tip. Wishing you and yours safety and health.
