### ISSUE TITLE
is it possible to reset password at!entercnd="password"?

### ISSUE THREAD

**Issue by gsmantenna** [bkerler/SierraWirelessGen#16]
I ever set at!entercnd password, but I forget.
is it openlock has Authority to change or reset it ?

**Comment by sand-rey** [comment]
AT!OPENCND?
CB11F27E0C60A366
sierrakeygen.py -c CB11F27E0C60A366 -d MDM9x50_V1
AT!OPENCND="650532C03D863020"
OK
AT!SETCND="A710"
OK
