### ISSUE TITLE
MC/EM7411 Possible?

### ISSUE THREAD

**Issue by oleteacher** [bkerler/SierraWirelessGen#18]
Wondering if one of the other models may be compatible with the MC/EM7411?

Tried a few and never got to work...

If not, would you consider adding the 7411? Becoming pretty popular with the bands it covers.

Thanks!

**Comment by bkerler** [comment]
Right now I couldn't find any firmware released for this device. As soon as we have a full dump or firmware release, I will have a look :)

**Comment by oleteacher** [comment]
I have been working from home far too long and gone mad crazy, lol. Could have sworn I added a link to firmware:

https://mega.nz/folder/60dDHYqL#-9nP9sn2ZKXpXt0NOe9t2w

All I have for the 7411. If there is anything else I can help with, let me know.

Also, when you have what you want from folder, like to remove the link...

**Comment by bkerler** [comment]
Thanks for the sdk, but we need a firmware for reverse engineering :)

**Comment by oleteacher** [comment]
Oh, that makes sense. I will see what I can do. If I were to get a full dump for you, how would I go about that?

**Comment by 2braincells2go** [comment]
> Thanks for the sdk, but we need a firmware for reverse engineering :)

How can I privately contact you @bkerler ? See reference to PM in other issues but d not see that as an option here.

**Comment by bkerler** [comment]
via twitter @viperbjk

Can you share the ATI response ?

-

**Comment by 2braincells2go** [comment]
> Can you share the ATI response ?

Traveling at the moment. Sent you PM @twitter

**Comment by bkerler** [comment]
The algo for the 7411 seems to be the mdm9x50 one (same as 7511)

**Comment by 2braincells2go** [comment]
> The algo for the 7411 seems to be the mdm9x50 one (same as 7511)

Great news! Thanks for taking time to check it out.

**Comment by 2braincells2go** [comment]
@bkerler Noticed the repository has moved. Can the new sierrakeygen.py be used same as version that use to be here?

Got to find the commands and how to use on my hard drive tomorrow - do not see them on new version @ https://github.com/bkerler/edl

Hey @oleteacher, wake up! Call me sometime tomorrow, know you traveling too.

**Comment by bkerler** [comment]
It's the same code ;) try ./sierrawireless -u

**Comment by bkerler** [comment]
Oh and it's in the edl/modem directory ;)

**Comment by oleteacher** [comment]
Thank you both for your help. Will give this a try when class resumes on Tuesday.
