### ISSUE TITLE
EM7565

### ISSUE THREAD

**Issue by 0xAA** [bkerler/SierraWirelessGen#3]
Could you add support for the Generic version of EM7565 (latest firmware)?

Thank you in advance...

**Comment by CitadelCore** [comment]
This would be awesome, if possible... I really need to disable FCC auth on my EM7565.

**Comment by bkerler** [comment]
I will have a look for the upcoming release :) Can you please post an example output of "AT!OPENLOCK?" and "AT!OPENMEP?" ?

**Comment by gsmantenna** [comment]
thanks for your reply , I will send you code tomorrow

Bjoern Kerler <notifications@github.com> 于2019年4月21日周日 下午5:01写道：

**Comment by bkerler** [comment]
Solved by commit 6cade1d
