### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by ghazish** [bkerler/SierraWirelessGen#5]
Could you please include the following device in your calculator Netgear MR1100-100EUS. 
I would like to ge the unlock code to use it with openlock command. 

Regards,
Ghazi

**Comment by bkerler** [comment]
For that I need a plain firmware file (dump) from the device, as the .secc.spk files seem to be encrypted.

**Comment by sgulls** [comment]
> For that I need a plain firmware file (dump) from the device, as the .secc.spk files seem to be encrypted.

I have the plaintext firmware dump for the boot loader and Qualcomm DSP, TZ, RPM partitions of this device.

**Comment by bkerler** [comment]
Solved by commit 6cade1d

**Comment by slipperyrails** [comment]
Apparenly the MDM9x50_V1 did not make it into the change to edl. Install from scratch Summer 2022, device MDM9x50_V1 not present

**Comment by edelberry** [comment]
@slipperyrails MDM9x50_V1 seems to be merged into MDM9x40. If you look at [this commit](https://github.com/bkerler/SierraWirelessGen/commit/2ae6258b9f2cef73dfbcac1712cbec1be05d8fac), it shows the previous line for MDMx50_V1 being removed, and it is the same as MDMx40, so you should be able to get whatever you need working using that identifier.

**Comment by slipperyrails** [comment]
Yes I eventually came up on that myself sorry for not canceling the request.
Thank you

**Comment by edelberry** [comment]
No prob, I was looking for this myself and found this, then figured it out so figured I would post to help someone out!

**Comment by legendboy78** [comment]
do you have prog_firehose_sdx20.mbn
