### ISSUE TITLE
MC7355?

### ISSUE THREAD

**Issue by djzort** [bkerler/SierraWirelessGen#6]
I have tried several of the MC7xxx devices with the openlock codes from my mc7355 but to no avail

Is it possible to support this device?

I tried the firmware it came with, then upgraded to 

Revision: 'SWI9X15C_05.05.58.00 r27038 carmd-fwbuild1 2015/03/04 21:30:23'
From https://source.sierrawireless.com/resources/airprime/software/airprime-em73xx_mc73xx-fw-package-latest-release/ (the Generic release)

**Comment by bkerler** [comment]
Hi,

I will release a new keygen very soon which will work fine ;)



Am 16. September 2019 15:55:13 MESZ schrieb Dean Hamstead <notifications@github.com>:
>I have tried several of the MC7xxx devices with the openlock codes from
>my mc7355 but to no avail
>
>Is it possible to support this device?
>
>I tried the firmware it came with, then upgraded to 
>
>Revision: 'SWI9X15C_05.05.58.00 r27038 carmd-fwbuild1 2015/03/04
>21:30:23'
>>From
>https://source.sierrawireless.com/resources/airprime/software/airprime-em73xx_mc73xx-fw-package-latest-release/
>(the Generic release)
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bkerler/SierraWirelessGen/issues/6

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by djzort** [comment]
Cant wait :)

**Comment by Rwestrem** [comment]
Will this new keygen work with the mc7455 and em7565?

**Comment by bkerler** [comment]
yes. including netgear mr1.

Am 26. September 2019 15:18:17 MESZ schrieb Rwestrem <notifications@github.com>:
>Will this new keygen work with the mc7455 and em7565?  
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bkerler/SierraWirelessGen/issues/6#issuecomment-535497930

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Rwestrem** [comment]
Any new updates on the mr1100, mc74xx and em75xx modems yet?  Looking forward to this.

**Comment by bkerler** [comment]
The solution is confirmed to work for all sierra wireless and mr1000. It will be released very soon.

Am 23. Oktober 2019 05:25:25 MESZ schrieb Rwestrem <notifications@github.com>:
>Any new updates on the mr1100, mc74xx and em75xx modems yet?  Looking
>forward to this.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/bkerler/SierraWirelessGen/issues/6#issuecomment-545248543

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by oleteacher** [comment]
Checking in to see if progress on new release? In no way rushing, just checking in:)

**Comment by bkerler** [comment]
very very soon :) approx. in one or two weeks

**Comment by bkerler** [comment]
Solved by commit 6cade1d

**Comment by djzort** [comment]
Amazing, thanks

**Comment by oleteacher** [comment]
@bkerler  I forgot to thank you for updating, THANK YOU!
