### ISSUE TITLE
EM7455 not working

### ISSUE THREAD

**Issue by artful172** [bkerler/SierraWirelessGen#7]
I check firmware:
9999999_9904609_SWI9X30C_02.20.03.00_00_GENERIC_002.017_000.exe
9999999_9904609_SWI9X30C_02.32.11.00_00_GENERIC_002.064_000.exe
9999999_9904609_SWI9X30C_02.33.03.00_00_GENERIC_002.072_000.exe

code v5 not working on modem EM7455, if you need, me ready help in debug

**Comment by bkerler** [comment]
Solved by commit 6cade1d
