### ISSUE TITLE
EM7305 not working

### ISSUE THREAD

**Issue by artful172** [bkerler/SierraWirelessGen#8]
me check old firmware
Revision: SWI9X15C_05.05.26.00 r21289 carmd-fwbuild1 2014/04/02 18:24:16

AT!UDPID?
!UDPID:
APP : 9041
BOOT: 9040

OK
AT!OPENLOCK?
468B0666BC464F16
OK
AT!OPENLOCK=D5E0F372D7F7BA4A
ERROR

AT!OPENLOCK?
03526CCCFEFE8172
OK
AT!OPENLOCK=4835FAF18A11E692
ERROR

AT!OPENLOCK?
6D44D0FFF827663F
OK
AT!OPENLOCK=3D26BD6E8D6F5C21
ERROR

AT!OPENLOCK?
E43AE9E31EB8A687
OK
AT!OPENLOCK=B45DB8CEB018F26A
ERROR

**Comment by bkerler** [comment]
Solved by commit 6cade1d
