### ISSUE TITLE
Invalid Requirement

### ISSUE THREAD

**Issue by oleteacher** [bkerler/SierraWirelessGen#9]
Far from a linux guru :)

Trying to get the SierraWirelessGen working on Windows 10 machine running Ubuntu 18.04. Have installed Python 3 and followed install instructions for SierraWirelessGen.

When I run pip3 install -r requirements.txt get error below:

```
me@Laptop:~/SierraWirelessGen$ pip3 install -r requirements.txt
Invalid requirement: 'pyserial=3.4'
= is not a valid operator. Did you mean == ?
```

Any tips apprecaited.

**Comment by bkerler** [comment]
Just do a git pull, I've fixed the file ;)

**Comment by oleteacher** [comment]
I had removed the =3.4 (or at least thought so) and tried to run without success. Must have not:)

Thank you for the help and fix!
